apiVersion: v1
kind: Pod
metadata:
  name: process-a
spec:
  containers:
    - image: aitorarjona/k8s-mmap-tests:latest
      imagePullPolicy: Always
      name: process-a
      command: [ "/bin/sh", "-ec", "sleep 1000" ]
      volumeMounts:
        - name: tmp
          mountPath: /tmp
      resources:
        requests:
          cpu: "100m"
          memory: "1Gi"
        limits:
          cpu: "100m"
          memory: "1Gi"
  volumes:
    - name: tmp
      hostPath:
        path: /tmp/mmap
        type: DirectoryOrCreate
---
apiVersion: v1
kind: Pod
metadata:
  name: process-b
spec:
  containers:
    - image: aitorarjona/k8s-mmap-tests:latest
      imagePullPolicy: Always
      name: process-b
      command: [ "/bin/sh", "-ec", "sleep 1000" ]
      volumeMounts:
        - name: tmp
          mountPath: /tmp
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "100m"
          memory: "256Mi"
  volumes:
    - name: tmp
      hostPath:
        path: /tmp/mmap
        type: DirectoryOrCreate