apiVersion: v1
kind: Pod
metadata:
  name: process-mmap
spec:
  containers:
    - image: aitorarjona/k8s-mmap-tests:latest
      imagePullPolicy: Always
      name: process-mmap
      command: ["/bin/sh", "-ec", "sleep 1000"]
      volumeMounts:
        - name: tmp
          mountPath: /tmp
      resources:
        requests:
          cpu: "100m"
          memory: "1Gi"
        limits:
          cpu: "100m"
          memory: "1Gi"
  volumes:
    - name: tmp
      hostPath:
        path: /hosthome/aitor/minikube_mount/
        type: DirectoryOrCreate
---
apiVersion: v1
kind: Pod
metadata:
  name: process-mem
spec:
  containers:
    - image: aitorarjona/k8s-mmap-tests:latest
      imagePullPolicy: Always
      name: process-mem
      command: ["/bin/sh", "-ec", "sleep 1000"]
