apiVersion: v1
kind: Pod
metadata:
  name: process-sender
spec:
  containers:
    - image: aitorarjona/k8s-mmap-tests:latest
      imagePullPolicy: Always
      name: process-sender
      command: ["/bin/sh", "-ec", "sleep 1000"]
      volumeMounts:
        - name: sock
          mountPath: /sock
  volumes:
    - name: sock
      hostPath:
        path: /tmp/sock
        type: DirectoryOrCreate
---
apiVersion: v1
kind: Pod
metadata:
  name: process-receiver
spec:
  containers:
    - image: aitorarjona/k8s-mmap-tests:latest
      imagePullPolicy: Always
      name: process-receiver
      command: ["/bin/sh", "-ec", "sleep 1000"]
      volumeMounts:
        - name: sock
          mountPath: /sock
  volumes:
    - name: sock
      hostPath:
        path: /tmp/sock
        type: DirectoryOrCreate
